#/************************************************************************************
#** File: - Makefile
#** VENDOR_EDIT
#** Copyright (C), 2008-2020, OPLUS Mobile Comm Corp., Ltd
#**
#** Description:
#**      1. Add for oplus router boost
#**
#** Version: 1.0
#** Date :   2020-05-09
#** TAG  :   OPLUS_FEATURE_WIFI_ROUTERBOOST
#**
#** ---------------------Revision History: ---------------------
#**  <author>                      <data>     <version >   <desc>
#** ---------------------------------------------------------------
#**
#************************************************************************************/

obj-$(CONFIG_OPLUS_FEATURE_WIFI_SLA) += oplus_router_boost.o
